### ISSUE TITLE
getting-started.md: manifest for astronomerinc/ap-airflow:0.7.5-2-1.9.0-onbuild not found

### ISSUE THREAD

**Issue by paulg-mscience** [astronomer/docs#112]
The Quickstart instructions found in docs/v0.9/getting-started.md fail with error:
manifest for astronomerinc/ap-airflow:0.7.5-2-1.9.0-onbuild not found

Steps to repro:
1) follow the quickstart instructions
2) error received when executing command "astro airflow start"

**Comment by paolaperaza** [comment]
Hi @paulg-mscience ! Thanks for reporting this. I was able to recreate the error you're seeing and found that this is unfortunately a known bug on our end that will be fixed with our next release.

Can you swap out that `FROM` statement in your Dockerfile to:

`FROM astronomerinc/ap-airflow:0.7.5-1.10.1-onbuild`

For anyone on Cloud (v0.7.5), that should do the trick. Can you let me know if that works for you? I'll make a note in our current getting started doc to account for that bug.

**Comment by paulg-mscience** [comment]
Hello paolaperaza, 
Yes making your suggested change to my Dockerfile worked for me.
Thank you very much!

**Comment by paolaperaza** [comment]
@paulg-mscience Great, happy to hear it! Thankfully not something we'll continue seeing in future releases, but I put up a small change to our docs in the meantime. Happy Airflowing :)
