### ISSUE TITLE
Remove Software Docs from Search Indexes

### ISSUE THREAD

**Issue by astro-rft** [astronomer/docs#1298]
To reduce confusion with users not explicitly looking for our Software product, we should remove Software docs from search indexes. A temporary removal has been submitted via Google Search Console.

**Comment by jwitz** [comment]
@astro-rft I have also noticed this and was about to implement this change a few weeks ago, but I know that a large part of our Software user base still finds our docs from google search rather than using Algolia. Is there any way for us to deprioritize/ split the Software index without entirely removing the ability for Software users to find docs via Google?

**Comment by astro-rft** [comment]
Seems like the deprioritization efforts haven't been successful. Understand the impact to Software users, but not worth it at the current impact to Astro users IMO.
