### ISSUE TITLE
Duplicate info on KubernetesPodOperator

### ISSUE THREAD

**Issue by RNHTTR** [astronomer/docs#1436]
**Affected Document:**

- https://docs.astronomer.io/astro/kubernetespodoperator
- https://docs.astronomer.io/learn/kubepod-operator
- https://docs.astronomer.io/software/kubepodoperator

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

It might be difficult to maintain both documents accurately. I recommend consolidating or adding more info to [the guide](https://docs.astronomer.io/learn/kubepod-operator). For example, the guide doesn't include an example on how to pass the `resources` argument to configure resource requests/limits like how the [KPO astro documentation does](https://docs.astronomer.io/astro/kubernetespodoperator#configure-task-level-pod-resources), which is one of the key benefits of KPO.

**Additional Notes:**

There seems to be substantial drift between the KPO docs for astro & software although the implementation after the prerequisites should be largely, if not entirely, the same.

**Comment by kwcanuck** [comment]
Hi, @kentdanas. I assumed that this was an issue that required your review. If you prefer that I tackle it, just reassign it to me. Thanks!

**Comment by kentdanas** [comment]
We just did a consolidation for Astro and Learn for this particular doc, in favor of the Learn concept guide (we removed the `Run KPO locally` astro doc). However, we'll still need the `Run KPO on Astro` doc because there are special considerations there that don't apply to OSS, and everything in Learn Airflow Concepts section is OSS-targeted.

For the Software one, I'm not sure about the differences here or if this just hasn't been kept up to date. I would think that this one would be more straight forward than the astro one and possible not required in addition to the OSS one. @jwitz any thoughts here?

**Comment by jwitz** [comment]
It's on me that the Software version of the KPO doc has lagged behind the Astro one, so at a minimum that doc should be updated to get all of the content/ copy changes in the Astro doc (minus the extra steps for pulling from a private registry). 

The Software doc still has some Software-specific info in there, such as setting **Extra Capacity** and importing your Deployment namespace. Don't think we can remove it at this stage. 

My main takeaway here is that all of the code examples in the product docs should be available in the Learn doc, but that's already pretty massive in size. @kentdanas Would it make sense to split the current KPO doc into two separate docs? 

- KPO usage (overview, purpose, code snippets)
- Setting up KPO (local testing, OSS private images steps, etc) 

We could then have our product docs only include the specific information required for setting up the KPO on each product.

**Comment by kentdanas** [comment]
Yeah I think it could make sense to split up the KPO guide. Maybe the existing one could become KPO usage and then we could have a tutorial for setting up KPO? Tagging @TJaniF here because we'll be directing some attention to this for an upcoming webinar in the next few weeks, so we can tackle the update at the same time.

**Comment by kentdanas** [comment]
@jwitz can we close this based on your recent PR with updates to the Learn and Astro KPO docs? I think that took care of the overlap there, not sure about the software doc though.

**Comment by jwitz** [comment]
I did a minor update to the Software doc just now that removes the duplicate intro with the Learn guide, so this can be closed now

**Comment by jwitz** [comment]
On second thought, the Software KPO doc needs a little more love. Let's keep this open until I address that in a more comprehensive PR

**Comment by jwitz** [comment]
Closed with hotfix a while back: https://github.com/astronomer/docs/commit/03c43a4244ccdec1b3858062fba819ede77ca2e0
