### ISSUE TITLE
Reconsider cluster modification docs /reference docs structure

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#1465]
**Affected Document:** https://docs.astronomer.io/astro/category/configure-cluster-resources

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** 

Let's have a more clear split between our action-oriented cluster docs and our reference cluster docs, and let's update our reference docs to have more clear language than "resources"

**Additional Notes:**

**Comment by kwcanuck** [comment]
@jwitz and @paolaperaza it's not clear to me what changes are required to the existing _Manage clusters_ section. The task topics (View/Create) are standalone topics and the reference information is captured below a single, parent topic - _Configure cluster resources_. 

The topic _Supported cluster modifications_ describes "...the cluster and Deployment-level modifications that require Astronomer support and can't be completed in the Cloud UI or with the Astro CLI". The following topics for AWS, Azure, and GCP all provide information about the default and supported cluster configuration settings.  All topics within the _Configure cluster resources_ section are refence topics. 

So, with the existing layout, there is already a "clear split between our action-oriented cluster docs and our reference cluster docs". Also, the term resources only appears a single time in the heading for _Configure cluster resources_.

To resolve this issue is changing or removing _resources_ from the section title all that is required? Would _Manage cluster configurations_ work better? Again, there are no tasks (numbered procedures) that users can complete within the existing _Configure cluster resources_ section.

To review why the existing structure appears the way that it does currently, see [PR 1327](https://github.com/astronomer/docs/pull/1327).

What is it specifically that needs to be changed?

**Comment by jwitz** [comment]
> So, with the existing layout, there is already a "clear split between our action-oriented cluster docs and (the) reference cluster docs". 

The lack of a clear split boils down to the fact that the menu is named "Configure Cluster resources" (Action), but all of the docs have reference information. 

> Again, there are no tasks (numbered procedures) that users can complete within the existing Configure cluster resources section.

It's not numbered, but I think [this topic](https://docs.astronomer.io/astro/modify-cluster#request-and-confirm-a-cluster-change) falls under what we'd consider a "task". The tittle of the doc should reflect that the doc contains the primary task for the user to complete so that they can update their cluster. 

> Is changing or removing resources from the section title all that is required?

I like the suggestion of "Manage cluster configurations", which I think should be the name of our current "Supported cluster modifications".  "Supported cluster configurations" should be the name of the menu that stores "AWS/ GCP / Azure" reference docs. Currently, it's confusing to just have those cloud names in the sidebar without context for how those differ, especially when "Supported modifications" applies to all three.
