### ISSUE TITLE
Cost/Resource Implications Documentation

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#1589]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

CRE are commonly approached by customers who are concerned about their costs. We need to be proactive in notifying them how much resource will be consumed with no Airflow deployments, and what the marginal resource consumption is for each Airflow deployment. 

We don't need to call out the cost per node, just what the required node count will be in each situation.

This should also include the implications of the (currently mandatory) canary DAG.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
cc @paolaperaza

**Comment by kwcanuck** [comment]
@paolaperaza or @dnarain-astro can you confirm that we want to document "how much resources will be consumed with no Airflow deployments, and what the marginal resource consumption is for each Airflow deployment"? Thanks!

**Comment by dnarain-astro** [comment]
We agreed during the last CRE/product call that this is a good idea.  Now that being said, a lot of this is tribal knowledge.  

I have built diagrams of data plane architecture, but these are pre-worker queue redesign and therefore no longer accurate.  

PS: While I am convinced such a doc needs to be written, I am not convinced it should be in the public domain; an official document that is provided to the customer on-demand might be more appropriate IMO.

**Comment by stuart23** [comment]
@sudarshan-uc has been doing some investigation here and he can help author this.

**Comment by sudarshan-uc** [comment]
hello team, 

I managed to get the average list of components created on all three clouds and tried to gather list of components required to maintain healthy cluster. The list of components and the bare minimum resources required is added in the [google spreadsheet](https://docs.google.com/spreadsheets/d/1GBx4Iaf7JC_Ix8noeiRtPpHKGzp5g2IV5Hq7duc3AWs/edit?usp=sharing). The resources I calculated is without considering any airflow deployment as the deployments can be configured by customer. Anything they configure via astro UI will be addition to what shown in the sheet. 

We are requesting to have such info in documentation so that we can justify where the resources are being consumed even though no deployment is running or when it is idling. We are not expecting to have detailed breakdown of all components like shown here but a rough calculation based on category such as monitoring, logging etc.

**Comment by dnarain-astro** [comment]
Sudarshan:

I think going down to the level of the pods is too much implementation
detail to share.

Customers aren't paying for fractions of a resource - they are paying for a
full resource.


What we should document is:
- a list of resources for running the cluster (VPC, EKS, dataplane node
pool, system node pool)
- guidance on the number of resources consumed by each deployment (e.g. 1
nodepool per worker queue, how the dataplane and system node pool scales up
with deployments)

This will allow them to plug things into the cloud cost calculator and
figure out how much they will be paying in cloud costs.


PS: the really tricky part is "how the system node pool scales up with
deployments" because this depends on #schedulers and resources given to the
scheduler.

**Comment by kwcanuck** [comment]
@paolaperaza your input would be helpful to determine the best way forward. What information do want to provide customers, and where should this information appear?

**Comment by kwcanuck** [comment]
@paolaperaza your guidance is needed to move this issue forward. . What information do want to provide customers, and where should this information appear?

**Comment by kwcanuck** [comment]
Closing this issue for now as numerous attempts to solicit the information necessary to move it forward have been unsuccessful.
