### ISSUE TITLE
Resources to be backed up using velero

### ISSUE THREAD

**Issue by VickyWinner** [astronomer/docs#1619]
Hi

 I am using velero to to backup astronomer per your recommendations.  However, I am not sure on what all the resources needs to be 
backed up so that restore can be efficient and astronomer is fully functional post restore.  I am referring to the document [here](https://github.com/astronomer/docs/blob/main/software/disaster-recovery.md?plain=1). Document can guide users on what resources 
to focus primary and also list optional resources etc.

**Comment by jwitz** [comment]
Hi @VickyWinner , thanks for opening this issue. In the doc you shared, it looks like we recommend the following:

```
To recover the Astronomer platform in the case of an incident, there are two main components that need to be backed up:

1. The Kubernetes cluster state
2. The Astronomer Postgres database
```

Can you be more specific about what information you wanted to find in the document. For example, do you need more information about the Kubernetes cluster state, or do you need setup steps for backing up these resources? Please let me know and I'll work with the Software team to improve the documentation.

**Comment by VickyWinner** [comment]
It may be that I am new to astronomer and doesn't know what AKS resources make up the astronomer platform running.  for ex. should I backup PVCs and PVs?  That feature is optional in velero but may be required by astronomer.

**Comment by jwitz** [comment]
Sorry @VickyWinner I don't have much experience with maintaining Software infrastructure myself, but the one doc that might be helpful to you is https://docs.astronomer.io/software/system-components. This has a list of all components running on the Astronomer platform. I _think_ all of these components have to be backed up in order to have a successful backup.

If you are a Software customer and need a more urgent/ specific response, I'd recommend to reaching out to [support](https://support.astronomer.io). Meanwhile I'll work with the Software team on publishing some more general guidance in this document.
