### ISSUE TITLE
Load code files into Docusaurus

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#1769]
We need to find a way to load our code samples directly from a hosted file instead of specifying the code directly in Markdown. This allows us to:

- Simplify the raw code view of docs
- Reuse code samples and update all samples at once
- Run parsing tests on the code to make sure that it will compile

**Comment by kwcanuck** [comment]
@jwitz you might already be aware of this functionality:

_You can not only import a file containing a component definition, but also import any code file as raw text, and then insert it in a code block, thanks to [Webpack raw-loader](https://webpack.js.org/loaders/raw-loader/). In order to use raw-loader, you first need to install it in your project:_

I'm not sure if this is the correct solution, but it appears close. See [Importing code snippets](https://docusaurus.io/docs/next/markdown-features/react#importing-code-snippets).

Related to code block rendering, this appears to be helpful functionality: [Multi-language support code blocks](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks).
