### ISSUE TITLE
Customer feedback: Mention the ./astro binary piece earlier in CLI doc

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#186]
**Affected Document:**
https://docs.astronomer.io/install-cli
**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ X ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Gen2 customer Get Amplio mentioned they were confused about the Step 4 note since it comes _after_ step 3 which directs a user to confirm the install with `astro version` - The user indicated he tried running this command and was confused when he was unable to confirm the install/version, and suggested that we move the tip in step 4 to be before step 3:
![image](https://user-images.githubusercontent.com/15913202/144877585-8c2433bd-17a5-458a-8d1d-5aa3a77fdd95.png)

**Additional Notes:**

**Comment by paolaperaza** [comment]
@aspain Thank you for adding this - good call-out. I just changed this doc such that:

- Step 3 tells you to run `astro version` but as `./astro version` so that the command is actually successful
- Then Step 4 tells you how to run commands "the better way"

We'll change this very soon when we publish the Gen2 binary and the CLI is available on Homebrew 🎉
