### ISSUE TITLE
Docs on using your own Auth0 and optionally configuring it to work w/ Okta

### ISSUE THREAD

**Issue by ryw** [astronomer/docs#2]

**Comment by callafeucht** [comment]
I would also greatly appreciate some documentation in this area.

**Comment by paolaperaza** [comment]
@vparekh94 I just threw these notes in given what I know and what I could tell from following the install, but feel free to adjust/correct/edit these. 

Happy to help break them out into different issues if you want to separate Okta, etc. but otherwise figured it might help to have them in one place.

**Comment by vparekh94** [comment]
@ianstanton 's doc closes this!
