### ISSUE TITLE
Update EKS versions in Documents 

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#218]
## What kind of documentation change are you requesting?
 
* **Fix to an existing document**: See below for what labels to add
  
#### _How severe is the problem?_
- [ ] Critical: The document has incorrect or missing information that is preventing customers from being successful (Add the `error/itf` label to this issue).
- [X] FYI: The document could benefit from a change, but there's nothing that's currently preventing customers from being successful without it (Add the `error/useful` label to this issue).
- [ ] Typo: There's a noticeable grammar, spelling, or formatting issue in a document (Add the `error/typo` label to this issue). 
  
#### _Describe your suggestion for the change. In addition, include links to any relevant existing documentation, support tickets, messages, or external content:_

Under Step 2 the current EKS version section lists:
Astronomer currently supports Kubernetes versions 1.14, 1.15, 1.16 and 1.17 on EKS. This should be updated or removed to point to our supported K8S table to prevent having to continue to update the supported EKS versions.

**Comment by danielhoherd** [comment]
I see issues in:
- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/next/05_customize-airflow/06_integrate-iam.md
- enterprise/next/01_get-started/02_faq.md
- enterprise/v0.16/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.16/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.16/05_customize-airflow/06_integrate-iam.md
- enterprise/v0.16/01_get-started/02_faq.md
- enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.23/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.23/01_get-started/02_faq.md
- enterprise/v0.23/05_customize-airflow/06_integrate-iam.md
- enterprise/v0.23/06_manage-astronomer/06_upgrade-to-0-23.md

This list was found via `git grep '1\.14'` which had only a few additional docs that we don't need to update because they are versions >0.16

**Comment by jwitz** [comment]
Thank you for the recon @danielhoherd , looks like the FAQ one might be a false positive (at least within the context of this issue) but I've gone ahead and made changes to the IAM role guides, as well as the most current installation guides.
