### ISSUE TITLE
New Worker Type: A40

### ISSUE THREAD

**Issue by cmarteepants** [astronomer/docs#2490]
### New Feature Description

We are launching the A40 worker type the week of July 5th. We will need to update our docs to reflect this. This will be:

CPU: 8
Memory: 16 GiB
Default Task Concurrency: 40

### Required Reviewers

@conorbev, @cmarteepants

### Links to Internal Info or Resources

https://github.com/astronomer/astro/issues/14132

### Release Date

Week of July 5th

**Comment by conorbev** [comment]
@jwitz @cmarteepants 

I believe that we are going to also change some of the ephemeral storage, right? So that some of the storage text would also change here: https://docs.astronomer.io/astro/resource-reference-hosted#worker-type

[Looks like the plan is for that to switch from 5 to 10](https://github.com/astronomer/astro/issues/14549)

Alternatively, I believe that we could update this page in product to include the ephemeral storage amounts:

https://files.slack.com/files-pri/T02J89GPR-F05EK617ALD/image.png

**Comment by cmarteepants** [comment]
I'm open to either. 

Pro of adding this to the UI: 
- Not everybody reads docs
- We won't forget to update this if/when this changes

Pro of adding this to docs:
- Less visual clutter in the UI
- It's the same value across the board, so feels redundant to list it with workers.

**Comment by jwitz** [comment]
I think it's good to have in the UI. We still don't have a lot of great documentation on using ephemeral storage in Astro, and AFAIK it's one of those features where it's easy to misuse it.

Either separately from this release or as part of it, we should have a dedicated doc about using ephemeral storage with some best practices/ code examples. I think the only one we have now is https://docs.astronomer.io/astro/kubernetespodoperator#mount-a-temporary-directory
