### ISSUE TITLE
Broken Link - `reference/default.yaml` does not exist in `/docs` repo

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#255]
**Affected Document:**
The `default configuration file` link on the [Apply a Config Change](https://docs.astronomer.io/enterprise/apply-platform-config#step-2-update-key-value-pairs) page leads to a 404 page not found with url: https://github.com/astronomer/docs/blob/main/enterprise/next/reference/default.yaml

**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

**Additional Notes:**

![image](https://user-images.githubusercontent.com/15913202/147505900-d6764202-b87e-4af4-8f7e-2294308205ef.png)

**Comment by paolaperaza** [comment]
@aspain Good catch here - sorry for this. In our old docs repo we had ported over a few yaml files from `houston-api` repo (private) so that Enterprise customers could reference the source code. Looks like we missed porting it over to the new repo.

@jwitz See if you can:

- Port over anything in the old `/enterprise/reference` directory that isn't accounted for to our new `/docs` repo, including the `default.yaml` file (pull latest version from `houston-api` repo)
- Replace the link in this doc (and others)

Can chat on Monday if I'm missing anything here!

**Comment by aspain** [comment]
@paolaperaza thanks for taking a look - I also don't have the ability to add labels - so apologies for those always coming in blank.
