### ISSUE TITLE
Discussion about Reference and topics that are more related to their main content

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2634]
This is an issue to track larger discussion about the org of top-level menus, starting from Reference.

Current items in Astro's Reference:
- Submit a support request
- Astro Runtime
- Global environment variables
- Audit Log fields
- Feature Previews
- Security
- Glossary

**Based on our discussion on July 31st, proposing the following for Reference:**

- Reference:
  - Submit a support request
  - Feature Previews
  - Security
  - Glossary

**Astro Runtime is a component of Astro - should be part of the Overview menu:**

- Overview
  - Architecture
  - Features
  - Key concepts
    - Components (Organization, Cluster, Workspace, Deployment, Teams, Users)
    - Astro Runtime
      - Architecture 
      - Maintenance policy

**Global environment variables is a component of Airflow - should be part of Deployment's sub-topic environment variables:**

- Deployment
  - Environment variables
    - Overview (what, and its use - conns, vars, Airflow conf and user-specific env vars)
    - Environment variables on Astro ( priority of env vars & Set Env vars - should include Cloud UI, CLI and Docker)
    - Global env vars

**Audit Log fields is part of Observability, proposing the following:**

- Observability
  - Organization
    - Audit Logs (this will include how to export Audit logs - from Administration - and the field reference for easy access for users)
    - Metrics
  - Deployment
    - DAGs
    - Metrics
    - Logs
  - Data Lineage
    - Concepts
    - Integrate with Astro
    - View Data Lineage
  - Alerts and Notifications
    - Astro alets
    - Email

**Comment by jwitz** [comment]
This is interesting, you've identified meaningful gaps in our current IA! some initial thoughts:

- Audit logs doesn't necessarily have to be an "Organization" metric. I think that can stay on its own so that we don't have to make submenus for each log type.
- Are "Audit logs" really an observability feature? You would never review those for day-to-day moderation of the platform because they're so detailed/ unstructured. 
- Astro Runtime docs should not be in the Overview. The maintenance and architecture docs are too detailed compared to the other docs in that menu. If anything, those should all go in "Develop" alongside "Upgrade Runtime", but I also like their current position in Reference.

We shouldn't do all of this work at once. I think the two most important/ agreeable changes we can make now are:

- Move "Audit logs" content together. My vote is to keep everything under Administration > Organization but I'm open to hearing the argument for Observability
- Create a new menu for environment variables. I like having an overview that explains when you should user Docker vs. the UI

**Comment by manmeetkaur** [comment]
- Reg: Audit logs
  - Agreed, not just an organizational metric, it includes info about other Astro components; but you need to be an Organization Owner to export those, and will be mostly used for audit/checks at an organization level. 
  - Might not be a day-to-day observability feature if we see it's current state in Astro, but it is still observability. It has a lot of potential and once API is released, this can be so useful for orgs and it can be developed in Astro as well. Even though today it is manual, it can be ingested to a database and reports can be produced from it just like we can do for Airflow from REST API .
- Reg: Astro Runtime
  - Agreed that Arch is too much detailed, but shouldn't we work on an Overview page ? let the maintenance and other details about support stay in Reference? I realized that today as well, when I was trying to link Astro Runtime to a page that describes it, but sadly there isn't any. And it is a very important component of Astro, the gist of Astro. w/o it no deployment will be there.

**Comment by jwitz** [comment]
Makes sense on both points!

**Comment by jwitz** [comment]
@manmeetkaur I made issues for the areas we discussed:

https://github.com/astronomer/docs/issues/2657
https://github.com/astronomer/docs/issues/2656
https://github.com/astronomer/docs/issues/2658

I think the information about "Key Concepts" needs more detail so I'm not writing an issue for that specifically yet. Do you feel like everything in this discussion has been resolved/ addressed enough to close it out?

**Comment by manmeetkaur** [comment]
@jwitz Thanks for creating individual issues. I think we can create a separate issue for Key concepts and I can add the details there. 

But before we close this out, we haven't talked bout the changes to the Observability menu. WDYT about those ?

**Comment by manmeetkaur** [comment]
closing this, as we have created issues for each subtopic
