### ISSUE TITLE
Docs for Azure Private Preview

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2713]
### Context

We're launching support for Astro as part of Azures Native ISV service: https://learn.microsoft.com/en-us/azure/partner-solutions/

In short, it's an exclusive marketplace where Azure customers can find the Astronomer listing and, without leaving azure, create an Astro account, cluster, and Deployment.

We're going into Private Preview next week and will support ~5 customers to test out the UX and backend of this medium. As part of that, we need documentation for those customers. Most of it is reused content, but some will be specific to Astro on Azure.

### Ask

Create a Notion doc (that we will deliver as PDF) that at minimum covers:

- Overview of Astro on Azure
- Steps to create an Org
- How Azure objects match to Astro (e.g. `Azure resource` to cluster)
- How to create an Org + Workspace + Deployment
- What to do next
- Notes on billing?

[THIS IS NOT READY TO BE WORKED ON] Both @conorbev and I will work on defining the details here over the next few days/weeks.

**Comment by conorbev** [comment]
Hey @paolaperaza @jwitz I made a google doc with some pretty rough ideas/notes of how the flow currently works: https://docs.google.com/document/d/1HBnr0_vdLe1J7Y-DZ54UQBPTYsZNcBx3bGANE-Hl3WQ/edit

I've given you both access to the Liftr subscription in Azure so these should hopefully allow you to try this out for yourselves.

As you'll see most of it is Azure related stuff and I therefore think it might be helpful to also share this with the Microsoft PM Reshmi and get feedback/input from her on it. Can we add people from outside Astronomer to notion pages? I wasn't sure on that and that's why I made this a google doc for now.

**Comment by conorbev** [comment]
@paolaperaza @jwitz Is the doc I linked enough to remove the blocked label here?

The private preview should be ready this week. We are still trying to identify customers for it but we will potentially need a customer facing PDF very soon.

**Comment by jwitz** [comment]
Sure we can get started! Only added the blocked label based on `[THIS IS NOT READY TO BE WORKED ON] `

**Comment by jwitz** [comment]
Doc has been developed, closing this out!
