### ISSUE TITLE
Workers on K8s Executor already have Astro env variables available

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2770]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://docs.astronomer.io/astro/kubernetes-executor#mount-secret-environment-variables-to-worker-pods

### The Issue or Context

Astro environment variables are already available to Worker Pods in K8s Executor. [Slack thread](https://astronomer.slack.com/archives/C01MCEU9EV7/p1692895708008429).

**Comment by lzdanski** [comment]
Might have a little scope creep that I could see fitting into this issue or needing its own- this topic (K8s executor) came up in a conversation about possible docs that need review/improvement in general. we can do it as a part of the Doc Types work (where we identify docs that can be edited a little to make examples of) instead of rolling it into this issue for sure, I just wasn't sure how related the work might be! 

- https://docs.astronomer.io/astro/executors-overview
- https://docs.astronomer.io/astro/kubernetes-executor 

Thoughts?

**Comment by manmeetkaur** [comment]
@lzdanski This issue is just to remove the extra steps mentioned to use the env variables, because they are by default mounted when using K8s executor. So I think we can resolve this independently of the improvement.

**Comment by manmeetkaur** [comment]
Blocked per the status in the PR #2814 . Needs more discussion
