### ISSUE TITLE
Administration sidebar

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2787]
**Current Setup:**

- Administration:

  - User access
    - Manage Organization users
    - Manage Workspace users
    - Configure Teams
    - Setup SSO
    - Setup SCIM provisioning
    - Manage domains
    - User permissions reference

  - Organizations
    - Organization API tokens

  - Workspaces
    - Configure Workspaces
    - Workspace API tokens

  - Clusters
    - Create a dedicated Astro cluster
    - Resource reference
    - Connect to external resources
      - AWS
      - Azure
      - GCP

  - Astro Hybrid
    - Hybrid overview
    - Install Astro Hybrid
      - AWS
      - Azure
      - GCP
    - Manage Hybrid Clusters
    - Hybrid cluster settings reference

  - Billing

**Problems:** 

1. No rule for menu titles? User access was earlier part of Organizations and I proposed to move it out as it applies to all the other Astro components as well. It seems now other topics can also come out similarly
2. Some menu just like organization and now deployment will have only 1 sub-topic

**Proposed setup:**

- Administration

  - User access (same no change)
    - Manage Organization users
    - Manage Workspace users
    - Configure Teams
    - Setup SSO
    - Setup SCIM provisioning
    - Manage domains
    - User permissions reference
  
  - Manage Astro components
    - Create a dedicated cluster
    - Manage Workspaces (should have create/update/delete workspace settings? what about the other overview part )
    - Transfer a Deployment
    - Resource reference
  
  - Networking & Authentication
    - Connect to external resources
      - AWS
      - Azure
      - GCP
    - Authorize Deployment
    - API keys and tokens (this will also mean that as part of consolidation of the Automation menu, deployment api keys and workspace and org api tokens come under one umbrella ?) 

  - Billing
 
  - Astro Hybrid (no change)
    - Hybrid overview
    - Install Astro Hybrid
      - AWS
      - Azure
      - GCP
    - Manage Hybrid Clusters
    - Hybrid cluster settings reference

**Comment by jwitz** [comment]
I think this is a good discussion to have! My thoughts: The "Manage Astro components" menu feels like a step backwards. We're going to end up with a lot of docs covering a lot of different topics all in one menu, making it harder for a user to discover what they need. 

When structuring the sidebars, I try to think about what kind of questions a user is asking as they're looking through the menu. I like the current structure because I'm making a bet that users are thinking "I need to do something on my Workspace" instead of "I need to manage an Astro component".

I also think the docs in "Networking & Authentication", like "Authorize a Deployment", could easily be in "Manage Astro components", making it hard for users to know where to go.

>No rule for menu titles? User access was earlier part of Organizations and I proposed to move it out as it applies to all the other Astro components as well. It seems now other topics can also come out similarly

I actually think the "User access" menu does follow a logical order. If we renamed it to "Users", there would be a clear path from User > Cluster in terms of management scope, with each menu having docs for a "component" of Astro. To me this structure seems intuitive, but I would like to hear more about why you think our users would struggle with it.  I'm more concerned with having a good user experience than a consistent logic for organizing topics.

> Some menu just like organization and now deployment will have only 1 sub-topic

I'm not too worried about this. We are building out more features that will rely on these menus, so they won't have only one doc for long. I see it as future-proofing by providing a home for those future docs.

**Comment by manmeetkaur** [comment]
I actually collapsed the Manage Astro components. I originally had this in mind:

- Manage Clusters
  - Create an Astro cluster
  - Resource reference

- Workspaces & Deployments
  - Create Workspace 
  - Update a Workspace
  - Transfer a Deployment

Or 

- Manage Clusters
  - Create an Astro cluster
  - Resource reference

- Workspaces
  - Create Workspace 
  - Update a Workspace

- Deployments
  - Transfer a Deployment
 
These are just suggestions for people who are new to Astro and are more familiar with generic terms and better to be discussed in a call. I am okay with whatever the team decides. cc:  @lzdanski and @paolaperaza

**Comment by manmeetkaur** [comment]
closing this and adding a notion doc.
