### ISSUE TITLE
Avoid invisible special characters

### ISSUE THREAD

**Issue by BasPH** [astronomer/docs#318]
**Affected Document:**
![image](https://user-images.githubusercontent.com/6249654/151012598-9abb455a-33ba-4aac-bf0f-ff5407793f52.png)

**Problem Type (Priority):**
Following https://github.com/astronomer/docs/pull/261 which caused trouble with all installs, I noticed there are now invisible ZWSP characters in several docs:

![image](https://user-images.githubusercontent.com/6249654/151011997-02fdc083-488f-44ea-8bae-788bd63b7ae5.png)
(screenshot from PyCharm)

Invisible chars break the file format and take a lot of time to debug.

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Have to process e.g. pre-commit hook or tool in CI/CD to find invisible special chars.

**Additional Notes:**

**Comment by jwitz** [comment]
@BasPH I turned on "Show invisibles" in Atom which seems to catch the two offending characters mentioned across these issues. Not sure if an entire CI/ CD pipeline is necessary at this stage - this CI/CD snippet hasn't been updated since I started at Astronomer, so I assume whatever text editors we're using now haven't produced any new invisible characters

@paolaperaza In vscode/ whatever editor you use, I'd recommend turning on a "Show invisible characters" setting so we can catch these in the future
