### ISSUE TITLE
List all standard roles in permissions table

### ISSUE THREAD

**Issue by BasPH** [astronomer/docs#3577]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://docs.astronomer.io/astro/user-permissions#workspace-roles

### The Issue or Context

There's a workspace accessor role, but this isn't listed in the table of permissions. Could we add that?

**Comment by lzdanski** [comment]
@BasPH the *Workplace Accessor* role was not added to the table because it will cause a table design break, resulting in users needing to scroll in order to see all columns- the `workspace accessor` column would be hidden behind a side-scroll if we added it. Since the role only permits users to view workspaces in organizations they belong to, and do not have any of the currently listed permissions in the table, we decided to not add it. 

If you're encountering user confusion, let us know and we can open it back up to discussion.
