### ISSUE TITLE
Difference between astrocloud and astro is slightly confusing

### ISSUE THREAD

**Issue by RNHTTR** [astronomer/docs#470]
**Affected Document:**
Docs navbar

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
I believe that the `astrocloud` cli refers to the fully-managed version of Astronomer, and `astro` refers to the self-managed version of astronomer. The confusing part is that `astrocloud` is defined under the `Astro` tab in the navbar, and `astro` is defined under `Software`. In my opinion, renaming the "Astro" button in the navbar to "Astrocloud" would help clear things up a bit.

What made me slightly more confused is that both versions are technically software; the distinction is the management of the software. That is, `astrocloud` is still software, but it's managed my Astronomer rather than the customer. Maybe rebranding what is currently "Astronomer Software" as "Astronomer Enterprise" would be clearer?

**Additional Comments**
<img width="883" alt="astrocloud" src="https://user-images.githubusercontent.com/25823361/157128582-615eef1b-e9ae-4466-b70e-b3f5ff3b189b.png">

<img width="527" alt="software" src="https://user-images.githubusercontent.com/25823361/157128848-46919afe-caef-4862-a5ec-a46ee1bca5ec.png">

**Comment by jwitz** [comment]
Hi @RNHTTR, unfortunately this is just a temporary quirk of our product naming that was recently announced:

- Astro, our managed cloud product, uses the Astro CLI (which, confusingly, has the `astrocloud` executable)
- Astronomer Software, our self-hosted product, uses the Astronomer CLI (v1 of our CLI, still uses the `astro` executable)

We are hoping to better align our product naming in the very near future. Since this isn't an explicit documentation issue, I'm going to close out this ticket.
