### ISSUE TITLE
Stay on same doc when switching from Software > Astro (if it exists)

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#619]
### Context

Request from Kevin Ruppel:

> Can we offer like a disambiguation link on some of the pages or make it so when I click astro at the top it takes me to the same page in the tree for astro (if it exists?)

Today, this is how it works:
- View Software doc for Secret backends
- Click "Astro" menu
- You're taken to Overview

### Idea

Ideally, this is how it would work:
- View Software doc for secret backends
- Click Astro menu
- Automatically taken to Astro version of secret backend doc, if it exists
- If it doesn't exist, go to Overview

**Comment by jwitz** [comment]
@kwcanuck @paolaperaza Yeah I really don't think this is possible nor desired behavior. We'd have to do a runtime check whenever a user clicks one of the navbar buttons, which sounds costly and likely to break with new Docusaurus versions. 

But more importantly, who is this process optimized for? The reason we duplicate docs between Astro and Software is because we want users to only ever have to use one docset. 

I see how this would be a benefit to Astronomer team members, but I actually think it would hinder the user experience by making it difficult to determine which product you're on and which doc you're viewing. Users should feel like they've entered a new product when they switch between those tabs, and having seamless transition between docs breaks down that product barrier.

**Comment by kwcanuck** [comment]
@jwitz thanks for the thorough feedback and analysis. 

@paolaperaza can we close this issue?

**Comment by kwcanuck** [comment]
@paolaperaza can we close this issue?

**Comment by paolaperaza** [comment]
Hey @kwcanuck @jwitz -- I think you two have come to a sensible conclusion that this isn't something we want to invest in making feasible, and might not be the best user experience in the first place.

I'll close this out! If it comes back up and our needs change over time, we can re-discuss. Thanks for the ping!
