### ISSUE TITLE
Wrong Info in "Integrate with Amazon SES" section of "Airflow Alerts"

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#631]
Doc: https://docs.astronomer.io/astro/airflow-alerts/#integrate-with-amazon-ses

From @ben-astro:

> Hey Docs team! I recently walked through setting up [Airflow alert emails via AWS SES on Astro](https://docs.astronomer.io/astro/airflow-alerts#integrate-with-amazon-ses), and the currently documented steps did not get me to working integration. Our docs go the route of using an smtp_default connection, but I don’t think it is being configured with all the necessary info.
> I’m not 100% sure what the minimum required set of values is, but Kenten and I found some old Zendesk cases with ENV VARs that DID work; looks like STARTTLS, SSL, and MAIL_FROM are the missing fields as compared to the connection configs in our docs.

```
ENV AIRFLOW__SMTP__SMTP_HOST=email-smtp.us-west-2.amazonaws.com
ENV AIRFLOW__SMTP__SMTP_STARTTLS=True
ENV AIRFLOW__SMTP__SMTP_SSL=False
ENV AIRFLOW__SMTP__SMTP_USER=<redacted>
ENV AIRFLOW__SMTP__SMTP_PASSWORD=<redacted>
ENV AIRFLOW__SMTP__SMTP_PORT=587
ENV AIRFLOW__SMTP__SMTP_MAIL_FROM=ben.garrison@astronomer.io
ENV AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
```

> As a related topic, in step 1 of our doc, we specify the following:
> `In the AWS Management Console, go to AWS Console > Simple Email Service > Email Addresses to add and verify the email addresses you want to receive alerts.`
> In my testing, I needed both the sender and receiver email addresses to be verified in AWS SES, not just the receivers as indicated here.

**Comment by ben-astro** [comment]
A couple other lesser suggestions for clarity of some of the steps: 

1) Regarding this line - not sure if its because AWS has renamed things (?), but this was not under "Email Addresses" but instead under "Verified Identities". 
> In the AWS Management Console, go to AWS Console > Simple Email Service > Email Addresses to add and verify the email addresses you want to receive alerts.
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/68117952/165348444-e45d62a3-c07d-4bf8-963e-363f853bac1b.png">

2) Regarding this line - this is probably more b/c AWS GUI is not great, but it took me a while to find the spot to create the SMTP Creds - it's located in the Simple Email Service > Dashboard, not in a menu/subdirectory which our doc seems to imply (see bottom of my image). Once I got there, it was straightforward to create necessary creds. 
> In the AWS Console, go to Simple Email Service > SMTP Settings and use the Create My SMTP Credentials button to generate a username and password. This will look similar to an access and secret access key. Write down this username and password for step 5, as well as the Server Name and Port.
<img width="977" alt="image" src="https://user-images.githubusercontent.com/68117952/165349357-8e40e85b-b0f1-4b8f-84cc-466af05b1676.png">

3) Regarding this line - I think this is currently just telling users to grab the region-code (like `us-west-1`), but then in following steps we're asking folks to provide the actual host URL - Might be worth calling out in this line that the region code will go into the host URL, and add an example host URL like `email-smtp.us-west-1.amazonaws.com` OR just change this to say "Grab the SMTP endpoint URL and use that for `SMTP_HOST` ENV VAR". 
> Choose an Amazon EC2 region to use, then write down the code of this server for the next step. Refer to [Amazon's list of available regions and servers](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions) to determine which server best fits your needs.
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/68117952/165350364-7487e263-272c-48c6-8507-8e3fe98d5eed.png">

**Comment by paolaperaza** [comment]
This is great @ben-astro - thanks so much for the detail. We'll get on it.

**Comment by kwcanuck** [comment]
Hi, @paolaperaza I know that you were working on issue #621 and it's related to the updates requested here. Can you confirm if _any_ of the changes requested in this issue have already been addressed? Thanks!

**Comment by ben-astro** [comment]
My review is done! left some comments in the Google Doc. Thanks @kwcanuck!

**Comment by kwcanuck** [comment]
Thanks for the quick review @ben-astro! I'll update the doc and use your recommendations.

**Comment by jwitz** [comment]
I just added review as well @kwcanuck , haven't done any inline editing yet but will do that once the PR is out!

**Comment by kwcanuck** [comment]
Thanks @jwitz!
