### ISSUE TITLE
NFS Installation on Azure clarification

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#696]
**Affected Document:**
https://docs.astronomer.io/software/deploy-nfs

**Problem Type (Priority):**

Azure NFS volumes should have more guidance then referring just to the Azure documentation

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
For this to work with Azure you need to use premium Azure file share, TLS requirement disabled, and enable NFS. There is an internal guide that should be incorporated into this document to help customers get this feature working quickly.

**Additional Notes:**

**Comment by jwitz** [comment]
@rbankston Can you share the Notion link for the internal guide?

**Comment by rbankston** [comment]
https://www.notion.so/astronomerio/NFS-Mount-for-AKS-417fcc897b6a40189e86dd46ba99ba25#7d6f2080150040e9af5e077c7ab5b489

**Comment by cmarteepants** [comment]
I don't love how the feature is documented and welcome improvements. I tried writing something up awhile ago, but gave up. The notion doc is veering into solution territory though. Even if I were to follow the instructions as is, it would be incomplete. 

1. We're suggesting to create a k8s deployment in the same cluster as the Astronomer, and mount the share with read/write privileges. We don't give context as to why (because our Airflow deployments mount the share as read-only) or provide guidance on how to get the dags into the mounted directory of the pod (because it'll depend)

2. There are other ways (like mounting the NFS share in a VM in your CICD pipeline) that are more appropriate, but less generic (and will heavily depend on your ecosystem). 

3. We're asking people to disable secure transfer, which makes me nervous. I would love to know if that's because of the approach we are recommending (k8s deployment in same cluster).

We should be documenting this publicly. But I'm becoming more convinced that we need a place for "Solutions" - which would be things like this and the DataDog integration request in Airflow.

**Comment by rbankston** [comment]
Agree on points 1 and 2 but  but it does fall into a it depends approach and into solutions territory for what is the best way for their ecosystem.

>3. We're asking people to disable secure transfer, which makes me nervous. I would love to know if that's because of the approach we are recommending (k8s deployment in same cluster).

Sadly for Azure that is required https://learn.microsoft.com/en-us/azure/storage/files/storage-files-how-to-mount-nfs-shares#:~:text=Select%20Disabled%20for%20Secure%20transfer%20required.

**Comment by cmarteepants** [comment]
> Sadly for Azure that is required https://learn.microsoft.com/en-us/azure/storage/files/storage-files-how-to-mount-nfs-shares#:~:text=Select%20Disabled%20for%20Secure%20transfer%20required.

Yeah I read that after. 

Plus, the PR's been merged. Think this can be closed
