### ISSUE TITLE
Accessing the Lineage API

### ISSUE THREAD

**Issue by conorbev** [astronomer/docs#714]
**Request type:**

- [x ] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

2 customers have asked about programatic access to their lineage data. This is actually already possible. Rough steps are described here: https://astronomer.productboard.com/feature-board/2193567-step-1-feature-backlog/features/12324494/detail

Perhaps we could have a simple page documenting how to do this underneath Reference --> Data Lineage ?

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes

**Comment by kwcanuck** [comment]
Discussed with @conorbev 2022-06-08 and this was his response:

_I actually think maybe we should icebox this ticket though for now though. Since the time I filed it there have been some discussions ( which haven't concluded yet ) about potentially wrapping all the Lineage related APIs in the main Astro API._

_i.e. in future maybe we won't expose the API that we currently do directly to customers._

_We should probably wait for that decision to be made before documenting widely._

When I requested confirmation that this issue should be closed, this was the response:

_yeah, let's just close for now. I'll file a new one if/when needed_
