### ISSUE TITLE
Add a Search Rule for Astro Runtime `-base`

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#733]
Some customers might wonder what the `-base` distribution of Astro Runtime is. Information is here: https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#distribution

However, if you search `base` in our Astro docs, the results are overwhelmingly references to the general word "base" or "based on". 

![image](https://user-images.githubusercontent.com/31111752/170497097-edb2f279-1389-4ac1-b584-4c2482e84ead.png)

Let's add a search rule that:
- On `base` or `Runtime base` or `-base`
- The following results should show up in this order:
     1. https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#distribution
     2. https://docs.astronomer.io/astro/develop-project#step-2-create-dockerfilebuild

**Comment by jwitz** [comment]
Confirmed this rule works! I went one topic more general for the private packages result, just because I thought it would be more clear why we were showing that result instead of linking directly to "Step 2" of a process
![Screen Shot 2022-06-03 at 2 19 14 PM](https://user-images.githubusercontent.com/74574233/171945812-2d4f4bee-6242-4489-8d13-68f2e893626d.png)
![Screen Shot 2022-06-03 at 2 19 36 PM](https://user-images.githubusercontent.com/74574233/171945872-3dc5dc33-5421-43b6-bef5-cbbecf66cf02.png)

I noticed that our other rule about `.env` got deleted 🤔 gonna keep tabs on these and see if that happens again, if it does might have a word with Algolia
