### ISSUE TITLE
Walkthrough RBAC permissions

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#80]
We should have a guide that walks users through how RBAC works on 0.9. This should include:

- Default permissions
- Adding users
- Removing users

**Comment by paolaperaza** [comment]
@vparekh94 Looks like you did a huge chunk of this a few months ago - I went in and cleaned up the formatting a bit and most recently renamed the doc from "Assigning Roles" to "User Roles and Permissions" and threw it under the "Using Astronomer" section (as it's not an EE-only doc).

Can you take a look and close this out if you feel good bout it?

https://preview.astronomer.io/docs/ee-rbac/

For Enterprise, it might be worth having a separate doc on how to leverage our API to make changes to users (e.g. adding them as sys admins, etc). What do you think?

**Comment by vparekh94** [comment]
Missed this - looks good -we should publish it asap. Can you get it on master today?

**Comment by paolaperaza** [comment]
@vparekh94 I had pushed straight to master on this one! Already on the nav, but I just pushed up a quick commit with a typo, clarifying phrase, and a reference to our source code for folks who want to know how Airflow native roles map to our RBAC.

Otherwise looks good to me - unless you want to add anything else EE specific, I'm ready to close if you are.
