### ISSUE TITLE
Update Set Environment Variables on Astro

### ISSUE THREAD

**Issue by kwcanuck** [astronomer/docs#957]
@frankcash indicated in a [Slack conversation](https://astronomer.slack.com/archives/C015V2JFKT5/p1658759604659899) that the existing topic _Set environment variables on Astro_ "...can be really confusing as it only details that environment variables for the purpose of airflow configuration can be set, when in reality the environment variables can be related to anything your code does". This led to a discussion with @jwitz and @paolaperaza on how best to resolve this concern. This is what is required to resolve this issue:

- Improving the existing overview to include a definition of what an environment variable is

- Adding a section for setting environment specific environment variables (local/production)

- Removing show Webserver = true

**Comment by frankcash** [comment]
👋   In python there is a stdlib way of accessing environment variables `os.getenv('...', default='default_value')`.  This simply reads in an environment variable.

There is a use case where accessing environment variables like this can be beneficial compared to calling `Variable.get('...')`, due to the fact that accessing an Airflow Variable will make a call to the secrets backend / metadata db.

An example of this is when we some form of code needs to only execute on a staging deployment or on a production deployment.

It is common to set an environment value of `ENV` or `ENVIRONMENT` to one of `staging, dev/local, prod` in a traditional software deployment (i.e. an API or other microservice).   If we set the environment value for `ENV` in the cloud UI  we can then access it w/ `os.getenv('ENV', 'dev')`.

![Screen Shot 2022-07-28 at 10 24 42 AM](https://user-images.githubusercontent.com/6012231/181546099-4ca3c55e-6f99-4736-995f-28db9d0ed550.png)

There could be other non airflow "related/configuration" environment variables that a customer may want to set as well, this is just a pretty generic example.
